### ISSUE TITLE
Ont balance is not same between command line and explorer

### ISSUE THREAD

**Issue by asfdg21** [ontio/ontology#691]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

When i query balance of `Ac8P8376ozoQ5H2Srcm32n5yb8kLoixRaP`  by command line, result is 383296 ; but in explorer, it's balance is 504296
This is the snapshot of my command line query : 
```
/bin # ./ontology asset balance Ac8P8376ozoQ5H2Srcm32n5yb8kLoixRaP
BalanceOf:Ac8P8376ozoQ5H2Srcm32n5yb8kLoixRaP
  ONT:383296
  ONG:9.9
```
This is the explorer page: https://explorer.ont.io/address/Ac8P8376ozoQ5H2Srcm32n5yb8kLoixRaP/20/1

So why this happened

**Comment by laizy** [comment]
make sure your local node has synchronized all the new blocks.

**Comment by asfdg21** [comment]
> make sure your local node has synchronized all the new blocks.

```
/bin # ./ontology info curblockheight
CurrentBlockHeight:1046533
/bin # ./ontology asset balance Ac8P8376ozoQ5H2Srcm32n5yb8kLoixRaP
BalanceOf:Ac8P8376ozoQ5H2Srcm32n5yb8kLoixRaP
  ONT:383296
  ONG:9.9
```

My node has synced

You may try this in your own node

**Comment by siovanus** [comment]
![image](https://user-images.githubusercontent.com/16396984/48603788-98189b00-e9b2-11e8-9a36-02da3590fcdb.png)
My own node is al right, and when you update your node to 1.5.1? I wonder that you may update your own node late, we add some new function after 1.0.4, and at that time your local node is also 1.0.3, so the transaction of new function will failed and have influence on later blocks, for example, the transaction change balance from  383296 to 504296 failed in your local node because of previous new function failure.

**Comment by siovanus** [comment]
So you can delete your Chain directory and sync with ontology 1.5.1 from the beginning.

**Comment by asfdg21** [comment]
> So you can delete your Chain directory and sync with ontology 1.5.1 from the beginning.

ok, i will try that

**Comment by asfdg21** [comment]
The problem has been fixed after resync chain, this issue can be closed
