### ISSUE TITLE
Consensus halt

### ISSUE THREAD

**Issue by Krestol** [ontio/ontology#806]
1.6.0-beta

The issue is actual for the latest release
The issue reproduces on Windows and Linux

Steps:
1. run 7 consensus nodes
2. suspend 4 of 7 consensus nodes
3. resume all suspended nodes

Expected Result :
New blocks appear in the blockchain

Actual Result:
Consensus halt is present. Now new blocks appear  in the blockchain

For running private network on Windows you can unpack archive [private_network.zip](https://github.com/ontio/ontology/files/2957943/private_network.zip), copy main.exe in it and run launch.cmd

**Comment by xiemylogos** [comment]
Hi Krestol.can you send your test log,I test 1.6.0-beta use your method, It looks like everything is ok. I review your https://github.com/ontio/ontology/pull/807 .but  There are some errors, use this pr in new consensus code ,the consensus halt. because your function getConsensusedCommittedBlockNum()   always return 0,false.

**Comment by Honglei-Cong** [comment]
fixed by #807
